Repository coding-test-break-through/algorithm, pull requests merged in 2024-01, with the labels that each got.

#2 [장유진] / 그리디 & 구현
  구현/게임_개발/jinchiim.py
  구현/럭키_스트레이트/jinchiim.py
  구현/문자열_압축/jinchiim.py
  구현/문자열_재정렬/jinchiim.py
  구현/왕실의_나이트/jinchiim.py
  그리디/1이_될_때까지/jinchiim.py
  그리디/곱하기_혹은_더하기/jinchiim.py
  그리디/동빈이의_큰_수의_법칙/jinchiim.py
  그리디/모험가_길드/jinchiim.py
  그리디/문자열_뒤집기/jinchiim.py
  그리디/숫자_카드_게임/jinchiim.py
Labels: 그리디, 구현

#3 [이혜린] / 그리디 & 구현
  .idea/.gitignore
  .idea/algorithm.iml
  .idea/modules.xml
  .idea/vcs.xml
  hyxrxn
  구현/게임_개발/hyxrxn.cpp
  구현/럭키_스트레이트/hyxrxn.cpp
  구현/문자열_압축/hyxrxn.cpp
  구현/문자열_재정렬/hyxrxn.cpp
  구현/왕실의_나이트/hyxrxn.cpp
  그리디/1이_될_때까지/hyxrxn.cpp
  그리디/곱하기_혹은_더하기/hyxrxn.cpp
  그리디/동빈이의_큰_수의_법칙/hyxrxn.cpp
  그리디/모험가_길드/hyxrxn.cpp
  그리디/문자열_뒤집기/hyxrxn.cpp
  그리디/숫자_카드게임/hyxrxn.cpp
Labels: 그리디, 구현

#7 [김보겸] / DFS&BFS
  DFS&BFS/DFS와_BFS/seedspirit.py
  DFS&BFS/경쟁적_전염/seedspirit.py
  DFS&BFS/괄호_변환/seedspirit.py
  DFS&BFS/미로_탈출/seedspirit.py
  DFS&BFS/연결_요소의_개수/seedspirit.py
  DFS&BFS/연구소/seedspirit.py
  DFS&BFS/음료수_얼려_먹기/seedspirit.py
  DFS&BFS/특정_거리의_도시_찾기/seedspirit.py
Labels: DFS&BFS

#8 [정해성] / 정렬 & 이진 탐색
  이진_탐색/가사_검색/haiseong.py
  이진_탐색/고정점_찾기/haiseong.py
  이진_탐색/공유기_설치/haiseong.py
  이진_탐색/떡볶이_떡_만들기/haiseong.py
  이진_탐색/부품_찾기/계수_정렬로_해결/haiseong.py
  이진_탐색/부품_찾기/이진_탐색으로_해결/haiseong.py
  이진_탐색/부품_찾기/집합(Set)_자료형으로_해결/haiseong.py
  이진_탐색/정렬된_배열에서_특정_수의_개수_구하기/haiseong.py
  정렬/국영수/haiseong.py
  정렬/두_배열의_원소_교체/haiseong.py
  정렬/성적이_낮은_순서대로_학생_출력하기/haiseong.py
  정렬/실패율/haiseong.py
  정렬/안테나/haiseong.py
  정렬/위에서_아래로/haiseong.py
  정렬/카드_정렬하기/haiseong.py
Labels: 정렬, 이진 탐색

#10 [장유진] / 정렬 & 이진 탐색
  정렬/두_배열의_원소_교체/jinchiim.py
  정렬/성적이_낮은_순서대로_학생_출력하기/jinchiim.py
  정렬/안테나/jinchiim.py
  정렬/위에서_아래로/jinchiim.py
  정렬/카드_정렬하기/jinchiim.py
Labels: 정렬, 이진 탐색

#9 [김보겸] / 정렬 & 이진 탐색
  이진_탐색/가사_검색/seedspirit.py
  이진_탐색/고정점/seedspirit.py
  이진_탐색/공유기_설치/seedspirit.py
  이진_탐색/떡볶이 떡 만들기/seedspirit.py
  이진_탐색/떡볶이_떡_만들기/seedspirit.py
  이진_탐색/부품_찾기/seedspirit.py
  이진_탐색/정렬된_배열에서_특정_수의_개수_구하기/seedspirit.py
  정렬/국영수/seedspirit.py
  정렬/두_배열의_원소_교체/seedspirit.py
  정렬/성적이_낮은_순서대로_학생_출력하기/seedspirit.py
  정렬/실패율/seedspirit.py
  정렬/안테나/seedspirit.py
  정렬/위에서_아래로/seedspirit.py
  정렬/카드_정렬하기/seedspirit.py
Labels: 정렬, 이진 탐색

#11 [정해성] / 정렬 & 이진 탐색 수정
  이진_탐색/가사_검색/haiseong.py
  이진_탐색/정렬된_배열에서_특정_수의_개수_구하기/haiseong.py
  정렬/국영수/haiseong.py
Labels: 정렬, 이진 탐색
